-- MySQL Script generated by MySQL Workbench
-- Thu 08 Sep 2016 16:30:00 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spazigwt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spazigwt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spazigwt` DEFAULT CHARACTER SET latin1 ;
USE `spazigwt` ;

-- -----------------------------------------------------
-- Table `spazigwt`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spazigwt`.`building` (
  `building_number` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `building_name` CHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`building_number`)  COMMENT '',
  UNIQUE INDEX `building_name` (`building_name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spazigwt`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spazigwt`.`role` (
  `role_id` INT(11) NOT NULL COMMENT '',
  `role_name` VARCHAR(30) NOT NULL COMMENT '',
  `role_weight` INT(11) NOT NULL DEFAULT '10' COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '',
  UNIQUE INDEX `role_name` (`role_name` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spazigwt`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spazigwt`.`person` (
  `person_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `person_name` CHAR(30) NOT NULL COMMENT '',
  `person_surname` CHAR(30) NOT NULL COMMENT '',
  `role_id` INT(11) NOT NULL COMMENT '',
  `start_work` DATE NULL DEFAULT '0000-00-00' COMMENT '',
  `end_work` DATE NULL DEFAULT '0000-00-00' COMMENT '',
  `email` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `phone` VARCHAR(15) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`person_id`)  COMMENT '',
  UNIQUE INDEX `person_email_uindex` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `person_phone_uindex` (`phone` ASC)  COMMENT '',
  INDEX `ibfk_4` (`role_id` ASC)  COMMENT '',
  CONSTRAINT `ibfk_4`
    FOREIGN KEY (`role_id`)
    REFERENCES `spazigwt`.`role` (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spazigwt`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spazigwt`.`room` (
  `room_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `room_code` VARCHAR(40) NOT NULL COMMENT '',
  `room_number` INT(11) NOT NULL COMMENT '',
  `room_floor` INT(11) NOT NULL COMMENT '',
  `building_number` INT(11) NOT NULL COMMENT '',
  `room_maxPeople` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `room_dimension` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `socket_network` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `maintenance` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`room_id`)  COMMENT '',
  UNIQUE INDEX `room_code` (`room_code` ASC)  COMMENT '',
  UNIQUE INDEX `room_number` (`room_number` ASC, `room_floor` ASC, `building_number` ASC)  COMMENT '',
  INDEX `ibfk_3` (`building_number` ASC)  COMMENT '',
  CONSTRAINT `ibfk_3`
    FOREIGN KEY (`building_number`)
    REFERENCES `spazigwt`.`building` (`building_number`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spazigwt`.`occupyroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spazigwt`.`occupyroom` (
  `occupyroom_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `person_id` INT(11) NOT NULL COMMENT '',
  `room_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`occupyroom_id`)  COMMENT '',
  UNIQUE INDEX `person_id` (`person_id` ASC, `room_id` ASC)  COMMENT '',
  INDEX `ibfk_7` (`room_id` ASC)  COMMENT '',
  CONSTRAINT `ibfk_6`
    FOREIGN KEY (`person_id`)
    REFERENCES `spazigwt`.`person` (`person_id`),
  CONSTRAINT `ibfk_7`
    FOREIGN KEY (`room_id`)
    REFERENCES `spazigwt`.`room` (`room_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
